[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = []

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "ahash", version = "0.7.6" },
  { name = "syn", version = "1.0" },
  { name = "indexmap", version = "1.9" },
  { name = "num_enum", version = "0.5" },
  { name = "hashbrown", version = "0.12" },
  { name = "bitflags", version = "1.3" },
  { name = "num_enum_derive", version = "0.5" },
  { name = "libloading", version = "0.7" },
  { name = "redox_syscall", version = "0.2" },
  { name = "regex-syntax", version = "0.6" },
  { name = "regex-automata", version = "0.1" },
  { name = "windows-sys", version = "0.45" },
  { name = "windows", version = "0.44" },
  { name = "windows_x86_64_msvc", version = "0.42" },
  { name = "windows_x86_64_gnullvm", version = "0.42" },
  { name = "windows_x86_64_gnu", version = "0.42" },
  { name = "windows_i686_msvc", version = "0.42" },
  { name = "windows_i686_gnu", version = "0.42" },
  { name = "windows_aarch64_msvc", version = "0.42" },
  { name = "windows_aarch64_gnullvm", version = "0.42" },
  { name = "windows-targets", version = "0.42" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
