[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = ["RUSTSEC-2020-0168"]

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"
allow = ["LicenseRef-UFL-1.0"] # For Ubuntu Light font from egui.

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "allow"
