[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "allow"         # TODO 0.9.1: Set to "deny".

[sources]
unknown-registry = "deny"
unknown-git = "allow"     # TODO 0.9.1: Set to "deny".
