[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
ignore = [
  "RUSTSEC-2021-0139", # Ignore ansi_term until there is a replacement
]

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "allow"
wildcards = "allow"         # TODO 0.9: Set to "deny" after release

[sources]
unknown-registry = "deny"
unknown-git = "allow"     # TODO 0.9: Set to "deny" after release
