[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = []

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "async-channel", version = "1.9" },
  { name = "async-lock", version = "2.8" },
  { name = "base64", version = "0.13" },
  { name = "bitflags", version = "1.3" },
  { name = "event-listener", version = "2.5" },
  { name = "fastrand", version = "1.9" },
  { name = "foreign-types", version = "0.3" },
  { name = "foreign-types-shared", version = "0.3" },
  { name = "futures-lite", version = "2.0" },
  { name = "hashbrown", version = "0.12" },
  { name = "indexmap", version = "1.9" },
  { name = "inotify", version = "0.9" },
  { name = "libloading", version = "0.7" },
  { name = "naga", version = "0.13" },
  { name = "num_enum", version = "0.5" },
  { name = "num_enum_derive", version = "0.5" },
  { name = "proc-macro-crate", version = "1.3" },
  { name = "redox_syscall", version = "0.3" },
  { name = "regex-automata", version = "0.1" },
  { name = "regex-syntax", version = "0.6" },
  { name = "regex-syntax", version = "0.7" },
  { name = "syn", version = "1.0" },
  { name = "toml_edit", version = "0.19" },
  { name = "tracing-log", version = "0.1" },
  { name = "windows", version = "0.48" },
  { name = "itertools", version = "0.11" },
  { name = "windows-sys", version = "0.45" },
  { name = "windows-targets", version = "0.42" },
  { name = "windows_aarch64_gnullvm", version = "0.42" },
  { name = "windows_aarch64_msvc", version = "0.42" },
  { name = "windows_i686_gnu", version = "0.42" },
  { name = "windows_i686_msvc", version = "0.42" },
  { name = "windows_x86_64_gnu", version = "0.42" },
  { name = "windows_x86_64_gnullvm", version = "0.42" },
  { name = "windows_x86_64_msvc", version = "0.42" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
