[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = []

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "bitflags", version = "1.3" },
  { name = "event-listener", version = "<5.1" },
  { name = "event-listener-strategy", version = "0.4" },
  { name = "foreign-types-shared", version = "0.3" },
  { name = "futures-lite", version = "2.0" },
  { name = "inotify", version = "0.9" },
  { name = "itertools", version = "0.11" },
  { name = "objc-sys", version = "0.2.0-beta.2" },
  { name = "objc2", version = "0.3.0-beta.3.patch-leaks.3" },
  { name = "objc2-encode", version = "2.0.0-pre.2" },
  { name = "redox_syscall", version = "0.3" },
  { name = "regex-automata", version = "0.1" },
  { name = "regex-syntax", version = "0.6" },
  { name = "syn", version = "1.0" },
  { name = "toml_edit", version = "0.21" },
  { name = "tracing-log", version = "0.1" },
  { name = "windows" },
  { name = "windows-core" },
  { name = "windows-sys" },
  { name = "windows-targets" },
  { name = "windows_aarch64_gnullvm" },
  { name = "windows_aarch64_msvc" },
  { name = "windows_i686_gnu" },
  { name = "windows_i686_msvc" },
  { name = "windows_x86_64_gnu" },
  { name = "windows_x86_64_gnullvm" },
  { name = "windows_x86_64_msvc" },
  { name = "winnow", version = "0.5" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
