[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.raw-coverage]
command = "cargo"
args = ["test"]
env = { RUSTC_BOOTSTRAP = 1, LLVM_PROFILE_FILE = "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/coverage/profile-%p.profraw", RUSTFLAGS = "-C instrument-coverage --cfg coverage" }

[tasks.coverage]
command = "grcov"
args = [
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/coverage",
  "--binary-path",
  "${CARGO_MAKE_CRATE_TARGET_DIRECTORY}/debug/",
  "--source-dir",
  "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}",
  "--excl-start",
  "mod tests",
  "--excl-line",
  "#\\[",
  "--ignore",
  "/*",
  "--ignore",
  "/*",
  "--ignore",
  "src/ui*",
  "--ignore",
  "*/main.rs",
  "--ignore",
  "src/core/cli.rs",                               # Contains some macro expansions that cannot be covered
  "${@}",
]
dependencies = ["raw-coverage"]
