[general]
name = "Vintage table"
license = "CC BY-SA 4.0"
author = "Yara Gardaria"
preview_translation = [0.0, -0.40, -1.5]

[object]
category = "Furniture"
components = [{ SideSnap = { half_width = 0.4 } }]
