[package]
name = "project_harmonia_widgets"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
bevy.workspace = true
bevy_simple_text_input.workspace = true

[lints]
workspace = true
