[general]
name = "Classic door"
license = "CC BY-SA 4.0"
author = "Yara Gardaria"
preview_translation = [0.0, -1.0, -2.9]

[object]
category = "Doors"
components = [
  { WallMount = { cutout = [
    [
      -0.4358678,
      0.0,
    ],
    [
      -0.4358678,
      2.0339782,
    ],
    [
      0.4358678,
      2.0339782,
    ],
    [
      0.4358678,
      0.0,
    ],
  ], hole = false } },
]
place_components = [
  { WallSnap = "Inside" },
]
spawn_components = [
  { Door = { half_width = 0.4, trigger_distance = 2.5 } },
]
