[general]
name = "Classic door"
license = "CC BY-SA 4.0"
author = "Yara Gardaria"
preview_translation = [0.0, -1.0, -2.9]

[object]
category = "Doors"
components = [
  { Door = { half_width = 2.0, trigger_distance = 2.5 } },
  { WallMount = { Embed = [
    [
      -0.4358678,
      1.1920929e-7,
    ],
    [
      0.4358678,
      1.1920929e-7,
    ],
    [
      0.4358678,
      2.0339782,
    ],
    [
      -0.4358678,
      2.0339782,
    ],
  ] } },
]
