[general]
name = "Classic door"
license = "CC BY-SA 4.0"
author = "Yara Gardaria"
preview_translation = [0.0, -1.50, -2.9]

[object]
category = "Windows"
components = [
  { WallSnap = "Inside" },
  { WallMount = { cutout = [
    [
      -0.7,
      0.830196,
    ],
    [
      0.7,
      0.830196,
    ],
    [
      0.7,
      2.33,
    ],
    [
      -0.7,
      2.33,
    ],
  ], hole = true } },
]
